name: "CI Workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Test
        run: go test ./... -ginkgo.v -coverprofile=coverage.txt --ginkgo.skip='pagination should detect volumes added between pages and accept tokens when the last volume from a page is deleted'
      - name: "upload test coverage report"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
